# -*- coding: utf-8 -*-
# Datos de cada página del libro para colorear.
SECTIONS = [
    ("arg", "Autos deportivos argentinos", "Autos hechos en Argentina, o por argentinos que hicieron historia.", "#74ACDF"),
    ("mundo", "Autos deportivos del mundo", "Las máquinas más famosas de Italia, Alemania, Estados Unidos, Francia, Inglaterra y Japón.", "#E4572E"),
    ("tc", "El TC de hoy", "El Turismo Carretera es la categoría más antigua del mundo que sigue corriendo: ¡empezó en 1937!", "#2E86AB"),
    ("hist", "Campeones históricos del TC", "Los pilotos que fueron leyenda con sus Dodge, Ford y Chevrolet.", "#F2A541"),
]

CARS = [
    # ---------------- ARGENTINOS ----------------
    dict(key="torino", sec="arg", name="IKA Torino 380W", year="1966", driver="Misión Argentina en Nürburgring (1969), con Fangio como jefe de equipo",
         flag="argentina",
         fact="En 1969 tres Torino viajaron a Alemania para correr las 84 Horas de Nürburgring: ¡84 horas seguidas, más de 3 días sin parar! Uno de ellos fue el auto que más vueltas dio en toda la carrera."),
    dict(key="zonda", sec="arg", name="Pagani Zonda", year="1999", driver="Creado por Horacio Pagani, de Casilda (Santa Fe)",
         flag="argentina",
         fact="De chico, Horacio Pagani hacía autitos de madera en Casilda. Después se fue a Italia y fabricó su propio superauto. Le puso Zonda por el viento caliente que sopla en Mendoza."),
    dict(key="huayra", sec="arg", name="Pagani Huayra", year="2011", driver="Creado por Horacio Pagani, de Casilda (Santa Fe)",
         flag="argentina",
         fact="Huayra quiere decir 'viento' en quechua. Tiene cuatro aletas que se mueven solas, como las alas de un pájaro, para frenar y doblar mejor."),
    dict(key="m250f", sec="arg", name="Maserati 250F", year="1957", driver="Juan Manuel Fangio, de Balcarce",
         flag="argentina",
         fact="Con un Maserati 250F como este, Fangio ganó en 1957 su quinto campeonato mundial de Fórmula 1. ¡Le decían 'El Chueco' y es uno de los mejores pilotos de la historia!"),
    # ---------------- MUNDO ----------------
    dict(key="f40", sec="mundo", name="Ferrari F40", year="1987", driver="Enzo Ferrari (fue el último auto que aprobó)",
         flag="italia",
         fact="Se llama F40 porque se hizo para festejar los 40 años de Ferrari. Fue el primer auto de calle que superó los 320 km/h."),
    dict(key="countach", sec="mundo", name="Lamborghini Countach", year="1974", driver="Diseñado por Marcello Gandini",
         flag="italia",
         fact="'Countach' es una palabra del norte de Italia que se dice cuando algo te sorprende, ¡como decir 'guau'! Sus puertas se abren hacia arriba, como tijeras."),
    dict(key="p911", sec="mundo", name="Porsche 911", year="1964", driver="Diseñado por Ferdinand 'Butzi' Porsche",
         flag="alemania",
         fact="Tiene el motor atrás, no adelante. Se fabrica desde 1964: ¡hace más de 60 años que existe y su forma casi no cambió!"),
    dict(key="gt40", sec="mundo", name="Ford GT40", year="1966", driver="Jacky Ickx y Jackie Oliver (ganadores de Le Mans 1969)",
         flag="eeuu",
         fact="Se llama GT40 porque mide solo 40 pulgadas de alto: ¡apenas 1 metro, como un nene de 4 años! Ganó 4 veces seguidas las 24 Horas de Le Mans (1966 a 1969)."),
    dict(key="chiron", sec="mundo", name="Bugatti Chiron", year="2016", driver="Lleva el nombre del piloto Louis Chiron",
         flag="francia",
         fact="Tiene 1.500 caballos de fuerza, ¡como 20 autos comunes juntos! Una versión especial llegó a casi 490 km/h."),
    dict(key="mclarenf1", sec="mundo", name="McLaren F1", year="1992", driver="Diseñado por Gordon Murray",
         flag="reinounido",
         fact="El conductor va sentado en el medio, ¡con un asiento para un amigo a cada lado! Durante años fue el auto de calle más rápido del mundo."),
    dict(key="mustang", sec="mundo", name="Ford Mustang", year="1964", driver="Creado por Lee Iacocca",
         flag="eeuu",
         fact="Lleva un caballo salvaje galopando en la trompa. ¡En su primer año se vendieron más de 400.000!"),
    dict(key="gtr", sec="mundo", name="Nissan GT-R", year="2007", driver="Apodado 'Godzilla'",
         flag="japon",
         fact="Le dicen 'Godzilla', como el monstruo de las películas japonesas. Cada motor lo arma a mano un solo maestro, llamado 'takumi'."),
    # ---------------- TC HOY ----------------
    dict(key="tc_camaro", sec="tc", name="Chevrolet Camaro ZL1", year="2025", driver="Agustín Canapino (campeón 2025)",
         flag="argentina",
         fact="Canapino es de Arrecifes, la 'Capital Nacional del Automovilismo'. ¡También corrió en Estados Unidos, en la IndyCar!"),
    dict(key="tc_mustang", sec="tc", name="Ford Mustang (TC)", year="2025", driver="Julián Santero",
         flag="argentina",
         fact="¿Ves el número 1? En el TC, el campeón del año anterior lleva el número 1 en su auto. Santero había ganado el campeonato 2024."),
    dict(key="tc_camry", sec="tc", name="Toyota Camry (TC)", year="2025", driver="Matías Rossi (Toyota Gazoo Racing)",
         flag="argentina",
         fact="Toyota es la marca 'nueva' del TC: durante muchísimos años solo corrieron Ford, Chevrolet, Dodge y Torino. A Matías Rossi le dicen 'El Misil'."),
    dict(key="tc_cherokee", sec="tc", name="Dodge Cherokee (TC)", year="2008", driver="Ernesto Bessone II",
         flag="argentina",
         fact="Aunque se llama Cherokee, ¡no es una camioneta! Es la versión moderna del Dodge con el que corrían campeones como Mouras y Castellano."),
    # ---------------- HISTÓRICOS ----------------
    dict(key="mouras", sec="hist", name="Dodge GTX de Roberto Mouras", year="1984", driver="Roberto Mouras: campeón 1983, 1984 y 1985",
         flag="argentina",
         fact="Le decían 'El Toro de Carlos Casares', su pueblo. Hoy el autódromo de La Plata lleva su nombre: Autódromo Roberto Mouras."),
    dict(key="castellano", sec="hist", name="Dodge GTX de Oscar Castellano", year="1987", driver="Oscar Castellano (Dodge / Ford): campeón 1987, 1988 y 1989",
         flag="argentina",
         fact="Su hijo Jonatan Castellano también es piloto de TC... ¡y también corre con Dodge! Esta foto es una réplica de su auto número 1."),
    dict(key="aventin", sec="hist", name="Ford Falcon de los Aventín", year="1991", driver="Oscar Aventín (Ford): campeón 1991 y 1992",
         flag="argentina",
         fact="Oscar y su hermano Antonio corrían los dos en el TC con Ford Falcon. Ford es la marca que más campeonatos ganó en la historia del TC."),
    dict(key="traverso", sec="hist", name="Chevrolet Chevy de Juan María Traverso", year="1995", driver="Juan María Traverso (Chevrolet): campeón 1995, 1996, 1997 y 1999",
         flag="argentina",
         fact="Le decían 'El Flaco' y es de Ramallo. ¡Con este mismo Chevy violeta ganó tres campeonatos seguidos!"),
    dict(key="ortelli", sec="hist", name="Chevrolet Chevy de Guillermo Ortelli", year="2011", driver="Guillermo Ortelli (Chevrolet): campeón 1998, 2000, 2001, 2002 y 2008",
         flag="argentina",
         fact="Es de Salto, provincia de Buenos Aires. Con este Chevy ganó otro campeonato más, en 2011: ¡es uno de los pilotos con más títulos de la historia del TC!"),
    dict(key="silva", sec="hist", name="Juan Manuel 'Pato' Silva", year="2005", driver="Juan Manuel 'Pato' Silva (Ford): campeón 2005",
         flag="argentina",
         fact="Le dicen 'el Pato'. Además del TC, ¡corrió el Rally Dakar, una carrera larguísima por desiertos y montañas!"),
    dict(key="moriatis", sec="hist", name="Ford Falcon de Emanuel Moriatis", year="2009", driver="Emanuel Moriatis (Ford): campeón 2009",
         flag="argentina",
         fact="Después de ser campeón, Moriatis armó su propio equipo de carreras, 'Moriatis Competición'. ¡Este Ford Falcon es uno de los autos de su equipo!"),
]

FLAGS = {
    "argentina": "Argentina", "italia": "Italia", "alemania": "Alemania", "eeuu": "Estados Unidos",
    "francia": "Francia", "reinounido": "Reino Unido", "japon": "Japón",
}
